# Generated by Django 4.1.6 on 2023-02-07 12:54

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=base.models.generate_pk,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
