# Generated by Django 4.1.6 on 2023-02-07 12:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.CharField(
                default=base.models.generate_pk,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
